server:
  port: 5000

aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_key: ${AWS_SECRET_ACCESS_KEY}
  endpoint: ${AWS_DYNAMO_ENDPOINT}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method

spring:
  security:
    filter:
      order: 1

jwt:
  secret: ${SECRET}
  expiration: ${JWT_EXPIRATION}
